### ISSUE TITLE
issue with typings

### ISSUE THREAD

**Issue by masnn** [filipedeschamps/rss-feed-emitter#202]
![image](https://user-images.githubusercontent.com/29992205/89642814-15064980-d8e7-11ea-8a0d-e7a789316489.png)

typescript v3.9.6  
node v14.7.0  
rss-feed-emitter v3.2.0

**Comment by TobiTenno** [comment]
If you delete the `types/src` folder out of your node modules, does it still do it?

also, if I give you the instructions, could you submit a PR for it? the owner is really slow at merging my PRs, but I can merge yours.

instructions:
- delete `types/src` folder on a branch
- add an empty `.gitkeep` file in `rss-feed-emitter/types`
- (commit changes)
- submit a PR

**Comment by TobiTenno** [comment]
alternatively, you can just fork and submit a pr from my types-fix branch back to master...

**Comment by masnn** [comment]
it works.

**Comment by masnn** [comment]
the typings file should be in types/src, but there are a copy in types. I think the best way is to delete them before publishing package.

**Comment by masnn** [comment]
no other change needed.

**Comment by filipedeschamps** [comment]
Hi @TobiTenno I've removed the necessary check, so now I think you can merge your own PRs 😍

**Comment by TobiTenno** [comment]
oh hey. i'll give that a shot

@masnn the ones in the base are the autogenerated ones that our publish process generates (to avoid storing them directly in the git repo)

**Comment by TobiTenno** [comment]
should be fixed, gonna wait to close this till the deployment is done and you can verify it, @masnn

**Comment by TobiTenno** [comment]
fix is released, could you check it for me, @masnn?

**Comment by masnn** [comment]
its fixed.

**Comment by masnn** [comment]
wait.. still have some problem.

FeedItem.d.ts L20 & L22 duplicate identifier 'FeedItem'

**Comment by masnn** [comment]
still the warning above

**Comment by TobiTenno** [comment]
that's odd, because it's tsc generating those type files at publish time

**Comment by TobiTenno** [comment]
could you screenshot for me? I don't use typescript in most of my development, so i'm just trying to make sure everything gets groovy for ya

**Comment by masnn** [comment]
> ![image](https://user-images.githubusercontent.com/29992205/89642814-15064980-d8e7-11ea-8a0d-e7a789316489.png)

not changed.

**Comment by masnn** [comment]
seems that ts doesn't allow namespace and class using the same name.

**Comment by TobiTenno** [comment]
odd... because those files (src/) don't exist anymore...

i dunno what else to do for it, cause tsc generates those... you'd think it'd make valid type defs....

**Comment by masnn** [comment]
i mean the same file, but not under src.
its under types/, but these content keeps the same.

**Comment by masnn** [comment]
like this 

![image](https://user-images.githubusercontent.com/29992205/89702127-26476880-d970-11ea-8edb-f0cca767bb17.png)

**Comment by TobiTenno** [comment]
ok, putting aside the location, since that's not the issue now, i'll have to toy around with the tsc config

**Comment by masnn** [comment]
is it fixed?

**Comment by TobiTenno** [comment]
No, I've not been able to find a different way to generate them that doesn't raise a duplicate error.

**Comment by TobiTenno** [comment]
If you could send me a gist with sample typescript of how you're using it so i can generate a project showing the same issues, that'd help a bunch.

**Comment by masnn** [comment]
What about write it directly instead of auto generate?

https://github.com/masnn/qqbot

just run `yarn` then `yarn build` .
you can see the messages above.

**Comment by TobiTenno** [comment]
Because I don't want to write them directly every time I make a change? The addition is to support ts usage, not to make it a burden.

**Comment by TobiTenno** [comment]
Got it sorted on some local generations, looks like typescript will properly respect type definitions, but not properly handle uniqueness. I'm checking the output for correctness and i'll put a new PR up

**Comment by TobiTenno** [comment]
Your build still fails for me, but not with errors from rss-feed-emitter on 3.2.2

**Comment by masnn** [comment]
3.2.2 works. thx.
